id: I113E92D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:35:46+00:00'
last_modified: '2022-06-08T11:57:36.560734+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD14769
  title: "རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་གྱི་འབྱེད་འགྲེལ་བདེ་ཆེན་ཞིང་དུ་བགྲོད་པའི་ཐེམ་སྐས་བཟང་པོ།
    \n"
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A9DD:
      image_group_id: I4PD936
      title: ''
      total_pages: 206
      order: 1
      base_file: A9DD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
