id: P009569
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD14769
  title: "རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་གྱི་འབྱེད་འགྲེལ་བདེ་ཆེན་ཞིང་དུ་བགྲོད་པའི་ཐེམ་སྐས་བཟང་པོ།\
    \ \n"
  author: ''
  volumes: {}
