id: P009569
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD14769
  title: "རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་གྱི་འབྱེད་འགྲེལ་བདེ་ཆེན་ཞིང་དུ་བགྲོད་པའི་ཐེམ་སྐས་བཟང་པོ།\
    \ \n"
  author: ''
  volumes:
    0d0a064ddd2143f8930ba04f378c9ece:
      image_group_id: I4PD936
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
